### ISSUE TITLE
Design Relational Database

### ISSUE THREAD

**Issue by sibsmc** [RailsGirlsCPH/mentor-mentee-platform#12]
Produce an entity relational diagram and make it accessible to everyone (wiki page might be a good idea).

Note that this issue covers only an initial version of the diagram. The diagram should evolve along with the product/code whenever changes are done to the underlying models.

**Current state of the issue/discussion**
The diagram can be seen and edited [here](https://www.lucidchart.com/documents/edit/164bd2c8-40ed-4797-acd6-e7d0e0a9c0d1/0?shared=true&)
Backend team has provided feedback and there has been some discussion with frontend team regarding its utility.

**Comment by diwanow** [comment]
Please share the diagram once you are ready in a wiki page.

**Comment by LoneKP** [comment]
[Mentor-mentee platform ERD.pdf](https://github.com/RailsGirlsCPH/mentor-mentee-platform/files/3015386/Mentor-mentee.platform.ERD.pdf)

That is our suggestion for an entity relationship diagram

Some comments on it:

**General considerations**
We have tried to make a split between what the users want (wishes table) and what they have done (experiences table). We believe this is the most crucial information to make matches between mentors and mentees

We have tried to keep it as simple as possible and with the "skateboard" in mind. 

**The one-user-type-two-user-type issue**
We have made it possible to mark users as either mentors or mentees, but have kept them in one user model. By doing it this way we can collect some information about whether the users want to be mentor/mentee or both. In the future we will then have the option to - if we want to - make separate user journeys. 

**Languages table**
Our thoughts behind putting languages as a separate table is that it can feed both experiences and wishes with possible programming languages that the user can select (to learn or teach).

**To be done**
We need to align this with the fields we wish to display in the frontend

**Comment by sibsmc** [comment]
I have suggested an update to the ERD shown above. 
The main changes made are moving the foreign keys to the tables with multiple entries per user, which are the wishes and experiences tables. 
And also setting up a one to one relationship between programming language and meeting frequency and the tables they are related to. 
Changes mean each user can have multiple wishes and experiences, but each of these wishes and experiences would relate to one particular programming language and one particular meeting frequency. 
https://www.lucidchart.com/documents/edit/164bd2c8-40ed-4797-acd6-e7d0e0a9c0d1?shared=true&#

**Comment by lujeanpierre** [comment]
I have update the ERD according to the project-backend thread on slack (removed the meeting frequency table)
https://www.lucidchart.com/documents/edit/164bd2c8-40ed-4797-acd6-e7d0e0a9c0d1/0?shared=true&

**Comment by lujeanpierre** [comment]
I am a bit confused about how issues and pull requests works together on GitHub. Should we open a PR in parallel of this issue to have an approval of the diagram by frontend ?

**Comment by diwanow** [comment]
> 
> 
> I am a bit confused about how issues and pull requests works together on GitHub. Should we open a PR in parallel of this issue to have an approval of the diagram by frontend ?

@lujeanpierre sorry for the confusion and thanks for the feedback - only by having such feedback we can improve, appreciated!

To answer the question, a Pull Request is necessary if the issue is about code or "artifacts" which live in the github repo and discussion in that respect. On the other hand an issue is a good place to have a discussion without code changes. So considering the nature of this "story", we are rather trying to set up kind of an architectural direction of where we are going so that we are aligned and here is discussion for it (it should rather happen here, not on slack). Also git is not particularly good at handling big binary files, so it might not be the best place to store the diagram (still a possibility, though, a matter of choice). Therefore, ultimately and as a result of this effort, I would expect the diagram or a view of it with link to edit to be embedded in a wiki page, for example, so that anyone can take a look and get an overview of that direction at any time, even without having to clone the repo. 

Finally, this issue here should give us some initial direction - the diagram itself will probably change with time as our understanding of what we want to build and how we want to build it evolves. Therefore, we don't necessarily need to spend a lot of effort to plan for every possibility we can imagine now. Going from there, every time we take decisions that affect the database model, implementing them would involve both making changes in code and in the diagram. It is indeed double effort and as such we should be smart about what we document, but documentation is part of development and I think it is good for everyone to get used to it.

As for getting an "approval" (I rather view it as getting people's attention and feedback, not as formal approval) by frontend, we can always just ping them like that:

@RailsGirlsCPH/frontend-team here is the suggested database diagram. It seems to be shaping up already, so we would love to hear your feedback too.

I hope that clears the confusion, let me know if you have further questions.

**Comment by lujeanpierre** [comment]
Thank you so much Dimitar for your answer :-)
So if I understand correctly, while an issue leads to a code change, we can open a PR to get an approval of the modifications. But in this particular case, it's not necessary to open a PR considering that Git doesn't really handle this kind of file and because it is not usefull to freeze the diagram.
Is it correct ?

**Comment by diwanow** [comment]
Correct :)

**Comment by sibsmc** [comment]
lucid chart of database added to readme in pull request #236
