### ISSUE TITLE
Components list

### ISSUE THREAD

**Issue by krem13** [RailsGirlsCPH/mentor-mentee-platform#24]
- Typography

#29 Heading (h1, h2, h3) / Paragraph (p16, p24...)
#31 Link
Error messages

- Forms

#26 Input field -  @krem13 
#27 Check box 
#28 Button
Images
#30 Avatar

- Diverse

Hashtag
Divider line

**Comment by diwanow** [comment]
Is it ok to close this issue? I created [a note on the front-end board](https://github.com/RailsGirlsCPH/mentor-mentee-platform/projects/2#card-19858388) with the same content as to me this scope didn't seem actionable on its own. If you agree, feel free to close it. If you think it has something more, please add it in the description, so that it is visible :)

**Comment by zoeyzou** [comment]
> Is it ok to close this issue? I created [a note on the front-end board](https://github.com/RailsGirlsCPH/mentor-mentee-platform/projects/2#card-19858388) with the same content as to me this scope didn't seem actionable on its own. If you agree, feel free to close it. If you think it has something more, please add it in the description, so that it is visible :)

It is fine to close it cuz I've created individual issues for each action point here. It's more like an overview
